//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by lynxmenu.rc
//
#define IDR_MAINFRAME                   101
#define IDR_ACCELERATOR1                103
#define IDR_MAINFRAME_CONTEXT_MENU      104
#define IDI_ICON1                       105
#define IDD_DIALOG1                     106
#define IDD_DUMPWIN_CONTEXT             106
#define IDD_TRACE                       110
#define IDD_ABOUT_BOX                   113
#define IDD_INFO_BOX                    114
#define IDD_WAITFORIT_BOX               115
#define IDD_WARNING                     116
#define IDB_BITMAP_BACKGROUND1          121
#define IDD_NETWAIT                     122
#define IDB_BITMAP_BACKGROUND2          122
#define IDD_NETADDRESS                  123
#define IDB_BITMAP_BACKGROUND3          123
#define IDD_KEYCONF                     124
#define IDD_KEYGET                      125
#define IDC_RADIO1                      1000
#define IDC_RADIO2                      1001
#define IDC_RADIO3                      1002
#define IDC_EDIT1                       1003
#define IDC_EDIT2                       1004
#define IDC_RADIO4                      1004
#define IDC_BUTTON1                     1008
#define IDC_KEYDEF_UP                   1008
#define IDC_BUTTON2                     1009
#define IDC_KEYDEF_DOWN                 1009
#define IDM_GETCMDLINE                  1009
#define IDC_CHECK1                      1010
#define IDC_KEYDEF_LEFT                 1010
#define IDC_CHECK2                      1011
#define IDC_KEYDEF_RIGHT                1011
#define IDC_EDIT3                       1012
#define IDC_KEYDEF_OPT1                 1012
#define IDC_EDIT4                       1013
#define IDC_KEYDEF_PAUSE                1013
#define IDC_EDIT5                       1014
#define IDC_KEYDEF_OPT2                 1014
#define IDC_EDIT6                       1015
#define IDC_KEYDEF_A                    1015
#define IDC_STATUS_FPS                  1016
#define IDC_KEYDEF_B                    1016
#define IDC_STATUS_EFF                  1017
#define IDC_STATUS_SPIN1                1018
#define IDC_STATUS_TARGET               1019
#define IDC_STATUS_SKIP                 1020
#define IDC_ABOUT_MANUFACTURER          1021
#define IDC_ABOUT_CARTRIDGE             1022
#define IDC_WARNING                     1024
#define IDC_WINUPD_NORM                 1025
#define IDC_WINUPD_FRAME                1026
#define IDC_WINUPD_CYCLE                1027
#define IDC_WINUPD                      1028
#define IDC_BPOINT0                     1029
#define IDC_BPOINT1                     1030
#define IDC_BPOINT2                     1031
#define IDC_BPOINT3                     1032
#define IDC_BPOINT4                     1033
#define IDC_BPOINT5                     1034
#define IDC_BPOINT6                     1035
#define IDC_BPOINT7                     1036
#define IDC_REG_PC                      1037
#define IDC_REG_SP                      1038
#define IDC_REG_PS                      1039
#define IDC_CYCLE_COUNT                 1040
#define IDC_WINUPD2                     1041
#define IDC_RUNSTAT_HALT                1042
#define IDC_RUNSTAT_STEP                1043
#define IDC_RUNSTAT_RUN                 1044
#define IDC_SPRITE_DEBUG                1047
#define IDC_ABOUT_BUILD                 1048
#define IDC_ABOUT_VERSION               1049
#define IDC_NETWAIT_TEXT                1050
#define IDC_NETWORK_ADDRESS             1051
#define IDC_REG_A                       1052
#define IDC_REG_X                       1053
#define IDC_REG_Y                       1054
#define IDC_REG_NMI                     1055
#define IDC_REG_IRQ                     1056
#define IDC_REG_WAI                     1057
#define IDC_REG_N                       1058
#define IDC_REG_V                       1059
#define IDC_REG_B                       1060
#define IDC_REG_I                       1061
#define IDC_REG_Z                       1062
#define IDC_REG_C                       1063
#define IDC_REG_D                       1064
#define IDC_KEYGET                      1065
#define IDC_EDIT_DBG1                   1066
#define IDC_EDIT_DBG2                   1067
#define IDC_EDIT_DBG3                   1068
#define IDM_CARTRIDGE_OPEN              40002
#define IDM_FILE_SNAPSHOT_GAME          40003
#define IDM_FILE_EXIT                   40004
#define IDM_FILE_OPEN                   40005
#define IDM_HELP_ABOUT                  40006
#define IDM_DEBUG_TRACE                 40007
#define IDM_DEBUG_DUMP                  40008
#define IDM_DEBUG_CODE                  40009
#define IDM_DEBUG_CLOSEALL              40010
#define IDM_OPTIONS_JOYSTICK            40011
#define IDM_OPTIONS_KEYBOARD            40012
#define IDM_OPTIONS_NORMAL_SIZE         40013
#define IDM_OPTIONS_SIZE_NORMAL         40014
#define IDM_OPTIONS_SIZE_DOUBLE         40015
#define IDM_OPTIONS_SIZE_TRIPLE         40016
#define IDM_OPTIONS_SIZE_QUAD           40017
#define IDM_OPTIONS_ROTATE_LEFT         40018
#define IDM_OPTIONS_ROTATE_RIGHT        40019
#define IDM_OPTIONS_FULL_SCREEN         40020
#define IDM_OPTIONS_WRESET              40021
#define IDM_OPTIONS_RESET               40022
#define IDM_OPTIONS_KEYDEFS             40023
#define IDM_OPTIONS_PAUSE               40024
#define IDM_DEBUG_WINUPDATES            40025
#define IDM_FILE_LOAD                   40026
#define IDM_HELP_INFO                   40027
#define IDM_OPTIONS_SOUND               40028
#define IDM_FILE_SNAPSHOT_BMP           40029
#define IDM_FILE_SNAPSHOT_RAW           40030
#define IDM_ESCAPE_FULLSCREEN           40031
#define IDM_DEBUG_GRAPHICS              40032
#define IDM_DEBUG_STEP                  40033
#define IDM_OPTIONS_BACKGROUND          40034
#define IDM_DRAW_DEBUG_WINDOWS          40035
#define IDM_OPTIONS_NETWORK             40036
#define IDM_OPTIONS_DISPLAY_MODE_1      40037
#define IDM_OPTIONS_DISPLAY_MODE_2      40038
#define IDM_OPTIONS_DISPLAY_MODE_3      40039
#define IDM_OPTIONS_DISPLAY_MODE_4      40040
#define IDM_OPTIONS_DISPLAY_MODE_5      40041
#define IDM_OPTIONS_DISPLAY_MODE_6      40042
#define IDM_OPTIONS_DISPLAY_MODE_7      40043
#define IDM_OPTIONS_DISPLAY_MODE_8      40044
#define IDM_OPTIONS_DISPLAY_MODE_9      40045
#define IDM_OPTIONS_DISPLAY_MODE_10     40046
#define IDM_OPTIONS_DISPLAY_FULLSCN     40047
#define IDM_OPTIONS_BACKGROUNDTYPE1     40049
#define IDM_OPTIONS_BACKGROUNDTYPE2     40050
#define IDM_OPTIONS_BACKGROUNDTYPE3     40051
#define IDM_DEBUG_RAMDUMP               40052
#define IDM_FILE_SNAPSHOT_LOAD          40053
#define IDM_DEBUG_DEBUGGER              40055
#define IDM_EDITLINE_INPUTWAITING       40056
#define ID_OPTIONS_USEBOOTROM           40057
#define IDM_OPTIONS_USEBOOTROM          40058
#define IDM_OPTIONS_RESETEEPROM         40059

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        126
#define _APS_NEXT_COMMAND_VALUE         40062
#define _APS_NEXT_CONTROL_VALUE         1069
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
